### ISSUE TITLE
Adição de Eventos de Mouse

### ISSUE THREAD

**Issue by DylanGuedes** [fgagamedev/ijengine#25]
Seria uma adição muito boa para a engine se fosse possível ter acesso aos eventos de mouse, diretamente na engine (de preferência com uma abstração parecida com a utilizada para eventos de teclado). Pensei em algumas formas, mas sempre esbarrava no fato de não poder chamar módulos da SDL2 diretamente.

**Comment by edsomjr** [comment]
Feito.
