### ISSUE TITLE
Não é possível executar o teste

### ISSUE THREAD

**Issue by mfurquimdev** [fgagamedev/ijengine#40]
Todos os passos para compilar e instalar a `ijengine` occorem sem nenhum erro, mas quando tento executar o teste, nada acontece e recebo uma mensagem `Kernel not found in libs dir`.

``` bash
$ cd ijengine
$ make
$ sudo make install
$ cd test
$ make
$ ./bin/test_game 
Kernel not found in libs dir
```

**Comment by edsomjr** [comment]
Furquim,

copie o arquivo kernel/sdl2/kernel.so para o diretório libs a partir do qual você vai executar o teste.

**Comment by mfurquimdev** [comment]
Funcionou, obrigado :)

``` bash
$ cd ijengine
$ make
$ sudo make install
$ cd test
$ mkdir libs
$ cp ../kernel/sdl2/kernel.so.0.1.0 libs/
$ make
$ ./bin/test_game 
```
